### ISSUE TITLE
6.1.2 Encriptar contraseña.

### ISSUE THREAD

**Issue by John-Ramirez** [xiomarapulido/Colombia-Feels#51]
Yo como usuario debo digitar una contraseña, para poder ingresar al sistema y la contraseña debe estar encriptada.

Tareas :

- [x] Alojar contraseña del usuario registrado en base de datos , con encriptacion md5 .

**Comment by felipechaux** [comment]
Tareas :

Alojar contraseña del usuario registrado en base de datos con encriptacion md5 .
