### ISSUE TITLE
1.1.2. Verificar Email.

### ISSUE THREAD

**Issue by John-Ramirez** [xiomarapulido/Colombia-Feels#52]
Yo como usuario del sistema debo digitar el email del usuario, para poder enviar notificaciones o solicitar cambio de contraseña, no se debe ingresar un email invalido.

Tareas :

- [x] Enviar notificaciones vía e-mail.
- [x] Recuperación de contraseña - modificación de la misma.

**Comment by felipechaux** [comment]
- [ ] Enviar notificaciones vía e-mail

**Comment by felipechaux** [comment]
- [ ] Enviar notificaciones vía e-mail.
- [ ] Recuperación de contraseña - modificación de la misma.
