### ISSUE TITLE
1.3.2 Rol maestro

### ISSUE THREAD

**Issue by xiomarapulido** [xiomarapulido/Colombia-Feels#71]
Yo como maestro, al loguearme en el sistema, me debe de mostrar todo el entorno que ha sido diseñado para mi, como: Mis alumnos, su progreso y calificaciones y el espacio para calificarlos.

**Comment by felipechaux** [comment]
Por favor considerar la eliminación de esta historia de usuario , no tendremos maestros que califiquen a los estudiantes ..
